2024-06-03 23:45:10,062 INFO    MainThread:60333 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-06-03 23:45:10,063 INFO    MainThread:60333 [wandb_setup.py:_flush():76] Configure stats pid to 60333
2024-06-03 23:45:10,063 INFO    MainThread:60333 [wandb_setup.py:_flush():76] Loading settings from /home/ray/.config/wandb/settings
2024-06-03 23:45:10,063 INFO    MainThread:60333 [wandb_setup.py:_flush():76] Loading settings from /home/ray/image-generation/SDXL/wandb/settings
2024-06-03 23:45:10,063 WARNING MainThread:60333 [wandb_setup.py:_flush():76] Unknown environment variable: WANDB_SETUP_API_KEY_HOOK
2024-06-03 23:45:10,063 WARNING MainThread:60333 [wandb_setup.py:_flush():76] Unknown environment variable: WANDB_PROCESS_RUN_INFO_HOOK
2024-06-03 23:45:10,063 WARNING MainThread:60333 [wandb_setup.py:_flush():76] Unknown environment variable: WANDB_POPULATE_RUN_LOCATION_HOOK
2024-06-03 23:45:10,063 INFO    MainThread:60333 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-06-03 23:45:10,063 INFO    MainThread:60333 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-03 23:45:10,063 INFO    MainThread:60333 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'text_2_image.py', 'program_abspath': '/home/ray/image-generation/SDXL/text_2_image.py', 'program': '/home/ray/image-generation/SDXL/text_2_image.py'}
2024-06-03 23:45:10,063 INFO    MainThread:60333 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-03 23:45:10,063 INFO    MainThread:60333 [wandb_init.py:_log_setup():520] Logging user logs to /home/ray/image-generation/SDXL/wandb/run-20240603_234510-9mlc1mbm/logs/debug.log
2024-06-03 23:45:10,063 INFO    MainThread:60333 [wandb_init.py:_log_setup():521] Logging internal logs to /home/ray/image-generation/SDXL/wandb/run-20240603_234510-9mlc1mbm/logs/debug-internal.log
2024-06-03 23:45:10,063 INFO    MainThread:60333 [wandb_init.py:init():560] calling init triggers
2024-06-03 23:45:10,063 INFO    MainThread:60333 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-06-03 23:45:10,063 INFO    MainThread:60333 [wandb_init.py:init():610] starting backend
2024-06-03 23:45:10,063 INFO    MainThread:60333 [wandb_init.py:init():614] setting up manager
2024-06-03 23:45:10,064 INFO    MainThread:60333 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-03 23:45:10,065 INFO    MainThread:60333 [wandb_init.py:init():622] backend started and connected
2024-06-03 23:45:10,067 INFO    MainThread:60333 [wandb_init.py:init():711] updated telemetry
2024-06-03 23:45:10,068 INFO    MainThread:60333 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-03 23:45:10,272 INFO    MainThread:60333 [wandb_run.py:_on_init():2396] communicating current version
2024-06-03 23:45:10,295 INFO    MainThread:60333 [wandb_run.py:_on_init():2405] got version response 
2024-06-03 23:45:10,295 INFO    MainThread:60333 [wandb_init.py:init():795] starting run threads in backend
2024-06-03 23:45:10,551 WARNING MainThread:60333 [wandb_init.py:init():1168] interrupted
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/ray/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/ray/anaconda3/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/ray/anaconda3/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/home/ray/anaconda3/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
